<?php

/**
 * @file
 *
 * This module demonstrates how to build various types of ctools plugins.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function plugin_test_ctools_plugin_directory($owner, $plugin_type) {
	if ($owner == 'ctools') {
		return "plugins/$plugin_type";
	}
}

/**
 * Implements hook_ctools_plugin_api().
 *
 * If you do this, CTools will pick up default panels pages in
 * <modulename>.pages_default.inc
 */
function plugin_test_ctools_plugin_api($module, $api) {
  if ($module == 'panels_mini' && $api == 'panels_default') {
    return array('version' => 1);
  }
  if ($module == 'page_manager' && $api == 'pages_default') {
    return array('version' => 1);
  }
}