<?php

/**
 * @file 
 * 
 * Shows examples of ctools plugins
 */


/**
 * Implements hook_ctools_plugin_type()
 * 
 * Here we tell the plugin system about the plugin types this module provides
 */
function calculation_plugins_ctools_plugin_type() {
  return array(
    'operation' => array(
      'use hooks' => TRUE,  
    ),  
  );
}

/**
 * Implements hook_menu().
 */
function calculation_plugins_menu() {
  $items = array();
  $items['operation_plugin'] = array(
    'title' => 'CTools calculation plugins example',
    'description' => t('CTools plugin example'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('calculation_plugins_calculation_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,  
  );
  return $items;
}

/**
 * Form builder for calculations demo page.
 */
function calculation_plugins_calculation_form($form, $form_state) {
  // Load all plugins of type "operation"
  ctools_include('plugins');
  $operations = ctools_get_plugins('calculation_plugins', 'operation');
  $operations_options = array();
  foreach ($operations as $id => $operation) {
    $operations_options[$id] = $operation['label'];
  }
  if (empty($operations_options)) {
    $form['message'] = array(
      '#markup' => t('Sorry no operation plugins available in the system'),  
    );
    return $form;
  }
  $form['operations'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Please choose operations'),
    '#options' => $operations_options,  
  );
  $form['number_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Number a'),  
  );
  $form['number_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Number a'),  
  );
  $form['number_a'] = array(
    '#type' => 'textfield',
    '#title' => t('Number a'),  
  );
  return $form;
} 
